/*
 * Copyright (c) 2021. Agency for Digital Government (DIGG)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package se.swedenconnect.ca.engine.ca.models.cert;

import java.security.PublicKey;
import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import se.swedenconnect.ca.engine.ca.issuer.CertificateIssuerModel;
import se.swedenconnect.ca.engine.ca.models.cert.extension.ExtensionModel;

/**
 * The model defining content in certificates to be issued
 * <p>
 * This model object only defines content data that is unique to the certificate being issued that is not generated by
 * the Certificate issuer instance.
 * <p>
 * Content that is common to all certificates such as validity period is defined by the {@link CertificateIssuerModel}
 * model
 *
 * @author Stefan Santesson (stefan@idsec.se)
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class CertificateModel {

  /** The name of the subject of the certificate */
  private CertNameModel<?> subject;

  /** The public key of the certificate subject */
  private PublicKey publicKey;

  /** Certificate extensions */
  private List<ExtensionModel> extensionModels;

}
